baseurl = "https://www.amanda-regan.com/Workshop-UCR/"
languageCode = "en-us"
title = "Text Analysis with Voyant Tools"
theme = "hugo-theme-bootstrap4-blog"
metadataformat = "yaml"

# number of posts to show on home/category/tag pages (Default: 10)
paginate = 5
# optionally override the site's footer with custom copyright text
# copyright = "Except where otherwise noted, content on this site is licensed under a [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by-sa/4.0/)."
#googleAnalytics = "UA-123-45"

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"



# Theme variables
#
[params]
  # Site author
  author = "Amanda Regan"

  # Description/subtitle for homepage (can be Markdown)
  description = "A Workshop at the University of California, Riverside"

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # verification string for Google Webmaster Tools
  #google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "66b077430f35f04a"

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    about = "This workshop is an introduction to text analysis for humanities scholars using Voyant Tools. We will begin by looking at a variety of text analysis projects and discuss numerous popular text analysis methodologies. We will then install the Voyant Server and explore the tools avialable while discussing the potential applications for teaching, research, and public humanities projects."

    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts = 0

  [params.social]
    # Optional, used for attribution in Twitter cards
    # See: https://dev.twitter.com/cards/types/summary-large-image
    twitter = "regan008"
    github = "regan008"

  [params.sharingicons]
    # Hide the sharing icons on posts? (Default: false)
    hide = false

    # Optionally, set any of these to false to hide them:
    #facebook = false

    #googleplus = false
    #linkedin = false
    #twitter = true

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]
