baseurl = "https://www.amanda-regan.com/Workshop-UCR/"
languageCode = "en-us"
title = "Voyant Tools Workshop"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Amanda Regan"
	description = "A text analysis workshop for the University of California Riverside"
	copyright = "Released under the MIT license"




	logo = ""
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "teal"

    [params.font]
    	text = "Open Sans"
    	code = "Ubuntu Mono"


[social]
	twitter = "regan008"
	email   = "aregan2@gmu.edu"


# [[menu.main]]
# 	name   = "Introduction"
# 	url    = "introduction/"
# 	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name = "Using Voyant Tools"
	url = "using-voyant/"
	weight = 20

[[menu.main]]
	name = "Resources"
	url = "resources"
	weight = 30

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
